---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines-maestro
  - name: pcf-pipelines

run:
  path: pcf-pipelines-maestro/tasks/maestro/task.sh

params:
  MAIN_CONCOURSE_URL: 
  MAIN_CONCOURSE_USERNAME:
  MAIN_CONCOURSE_PASSWORD:
  MAIN_CONCOURSE_SKIP_SSL:
